spring:
  profiles:
    active: dev
  application:
    name: Template
  messages:
    basename: i18n.messages
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://${config.jdbc.url}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${config.jdbc.username}
    password: ${config.jdbc.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20 # 连接池最大连接数，默认是10
      auto-commit: true # 控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: MyHikariCP #连接池名称，用于日志检索
      idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 1800000  # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 10000
      connection-test-query: SELECT 1

server:
  servlet:
    context-path: /
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
    max-connections: 1000
    accept-count: 100
    basedir: ${logging.file.path}/tomcat
    accesslog:
      enabled: true
      directory: access
      buffered: true
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      suffix: .log
      request-attributes-enabled: false
      pattern: common
    threads:
      min-spare: 10
      max: 50
    connection-timeout: 6000


mybatis-plus:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.gongbo.template.**.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      select-strategy: not_empty

